### ISSUE TITLE
Namespace-scoped packages

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#803]
In the current state, Glasskube packages can only be installed once per cluster. In some situations, this is an unnecessary restriction and limits some use-cases. 

It should be possible for the author of a package to specify a "scope", which can either be "Cluster" or "Namespaced" (default "Cluster"). Depending on a packages scope, the Glasskube system should create either a cluster or namespace scoped custom resource. The name of the cluster-scoped CRD is `ClusterPackage`, the name for the namespace-scoped CRD is `Package`. This is a breaking change, because we already currently the `Package` CRD name for the cluster-scoped resources, but we settled on this to stay consistent with common Kubernetes nomenclature (e.g. `Role`/`ClusterRole`). This change will be accompanied by an API version bump to `v1alpha2`. Existing installations can not be migrated automatically.

### Tasklist
- [ ] Refactor the codebase to support `ClusterPackage` and `Package`
- [ ] Update the dependency manager to allow `Package` validation
- [ ] Add UI for `Package` list, installation
- [ ] Update `install` command to allow creating `Package`
- [ ] Update `update` command to allow updating `Package`
- [ ] Update `configure` command to allow updating `Package`
- [ ] Update `describe` command to show status of all `Package` instances
- [ ] Update `list` command to show all `Package` instances
- [ ] Update `open` command to support `Package`
- [ ] Update `uninstall` command to allow deleting `Package`
- [ ] Update `autoupdate` commands to handle `Package`

### Limitations
* For now, dependencies must always be Cluster scoped, even for namespace scoped packages
